[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
token_sale = "8485PZTPiULpLaFxxRtuQHEK76m7oqeYLM3Bm5h4S6y7"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/AnchorProjects/token-sale/target/wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 src/**/mocha.ts"
